export const CREATE_QUESTION_POST = 'CREATE_QUESTION_POST';
export const FETCH_ONE_QUESTION_POST = 'FETCH_ONE_QUESTION_POST';
export const UPDATE_QUESTION_POST_UPVOTE = 'UPDATE_QUESTION_POST_UPVOTE';

