export const FETCH_MANY_PARTNER_REQUEST = 'FETCH_MANY_PARTNER_REQUEST';
export const ADD_ONE_PARTNER_REQUEST = 'ADD_ONE_PARTNER_REQUEST';
export const REMOVE_ONE_PARTNER_REQUEST = 'REMOVE_ONE_PARTNER_REQUEST';
export const ACCEPT_ONE_PARTNER_REQUEST = 'ACCEPT_ONE_PARTNER_REQUEST';
