export const FETCH_MANY_COMMENTS = 'FETCH_MANY_COMMENTS';
export const ADD_ONE_PARENT_COMMENT = 'ADD_ONE_PARENT_COMMENT';
export const ADD_ONE_SUB_COMMENT = 'ADD_ONE_SUB_COMMENT';
export const SWITCH_PARENT_COMMENT_LIKE_REACTION = 'SWITCH_PARENT_COMMENT_LIKE_REACTION';
export const SWITCH_SUB_COMMENT_LIKE_REACTION = 'SWITCH_SUB_COMMENT_LIKE_REACTION';