export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_BAD_REQUEST = 'LOGIN_BAD_REQUEST'
export const LOGIN_FORBIDDEN = 'LOGIN_FORBIDDEN'
export const LOGIN_SERVER_ERROR = 'LOGIN_SERVER_ERROR'
export const LOGOUT = 'LOGOUT';
